### ISSUE TITLE
Error invalid Syntax

### ISSUE THREAD

**Issue by Legion07** [Kuucheen/KC-Scraper#1]
```
root@ubuntu-s-4vcpu-8gb-fra1-01:~/Desktop/Scripts/KC-Scraper# python KC-Scraper.py
  File "KC-Scraper.py", line 56
    premades = input(f"{white}[{color}^{white}] {color}Use premades [y/n] {white}>> {color}")
                                                                                           ^
SyntaxError: invalid syntax 
```

I get this error everytime when i start it.

**Comment by Kuucheen** [comment]
i think for ubuntu you have to type "python3 KC-Scraper.py"
or perhaps you need to reinstall python3 and try both "python KC-Scraper.py" and "python3 KC-Scraper.py"

if you still have issues dm me on discord Kuchen#2472
