### ISSUE TITLE
automate the questions

### ISSUE THREAD

**Issue by maikelrichard** [Kuucheen/KC-Scraper#2]
how can i automate the questions, in a way that it executes directly
premade = y
http = 1
remove not connec... = n
remove site.. = n
threads = 3

**Comment by Kuucheen** [comment]
there is no yes in premades you can use 1 for http.txt
if Im right this should be what you want (copy it in settings.yaml);
{
    premades: "1", 
    removewebsites: "n",
    removeproxyless: "n", 
    threads: "3" 
}

**Comment by maikelrichard** [comment]
thanks for fast response
