### ISSUE TITLE
AttributeError: module 'ctypes' has no attribute 'windll'

### ISSUE THREAD

**Issue by miadabdi** [Kuucheen/KC-Scraper#3]
I have installed the requirements, running with python3 gives me an error.
Python 3.11.4
```
AttributeError: module 'ctypes' has no attribute 'windll'
```

![image](https://github.com/Kuucheen/KC-Scraper/assets/50056491/837270db-89cd-4171-b225-4d5a3d4f3e59)

**Comment by Kuucheen** [comment]
download the latest release, it should be fixed now

dont forget to reinstall requirements

**Comment by miadabdi** [comment]
It's fixed and working, thanks.
